name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main  # Adjust if you want to deploy from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }} # usually 'ubuntu' for Ubuntu AMIs
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu
            chmod +x deploy-frontend.sh
            ./deploy-frontend.sh

      - name: Send Telegram notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="✅ Heyy SURESH Frontend deployment to AWS EC2 completed successfully from *main* branch!" \
            -d parse_mode=Markdown
